### ISSUE TITLE
Just a little request

### ISSUE THREAD

**Issue by Skryzor009** [dosaki/strange-homeworlds#4]
Could you please add the "Strange Homeworlds + Complete Colors" mod here too?

**Comment by dosaki** [comment]
Will do. 

Haven't had time yet to do the compatibility patches.

Sorry!

**Comment by Skryzor009** [comment]
Thank you very much! You're awesome.

**Comment by dosaki** [comment]
Oh, I've done it already: http://steamcommunity.com/sharedfiles/filedetails/?id=717639819&searchtext=Complete+Colors
