### ISSUE TITLE
Toxic Homeworlds/Gas Giant Bug

### ISSUE THREAD

**Issue by Runarisu** [dosaki/strange-homeworlds#6]
Selecting Toxic homeworlds or gas giants causes all animations to freeze and doesn't display images if you select the homeworld, even on the main menu.

visible here 
https://puu.sh/rJLp8/8452938a60.jpg
with this image if I click another empire in my list which has working animations + backdrop and then click the one with the toxic homeworld the image freezes over and stays with it until I click another faction.
and here
https://puu.sh/rKEM1/18b716fa35.jpg

maybe just copy-paste the image from Tomb Worlds for now? Which looks like a Tundra city

I did some compatibility tests with various other mods and even though i run a fairly heavily modded game even just colonize unlimited + strange homeworlds unlocked causes this issue to occur.

**Comment by dosaki** [comment]
This is caused by #1.

I haven't figured out how to get an image to appear.
There's no setting for it at the moment I think.
