### ISSUE TITLE
a few of the techs are missing l10n text

### ISSUE THREAD

**Issue by db48x** [dosaki/strange-homeworlds#7]
Specifically, tech_planet_modernization and tech_hollow_asteroids. The strings appear to be missing in all languages, including english.

**Comment by dosaki** [comment]
I'm on it.

**Comment by dosaki** [comment]
[Fixed](https://github.com/dosaki/strange-homeworlds/commit/e0dd76d3bb424dd757e0d1f5439e04dbfa37f242)

**Comment by db48x** [comment]
Thanks :)
